### ISSUE TITLE
FIREBASE WARNING: Exception was thrown by user callback. TypeError: div.querySelector is not a function

### ISSUE THREAD

**Issue by codesdk** [firebase/friendlychat-web#217]
Am using firebase 3.9.0

==> firebase version
3.9.0

After following the steps till step7 here

https://codelabs.developers.google.com/codelabs/firebase-web/#7

Running the code in web, I get the following errors

`firebase.js:328 Uncaught TypeError: div.querySelector is not a function`

```
Uncaught TypeError: div.querySelector is not a function
    at FriendlyChat.displayMessage

```

and the following warning 

`FIREBASE WARNING: Exception was thrown by user callback. TypeError: div.querySelector is not a function
`

when I try to type a message into the chat text field.

Full trace

FIREBASE WARNING: Exception was thrown by user callback. TypeError: div.setAttribute is not a function
    at.displayMessage (http://localhost:5000/scripts/main.js:226:9)
    at .<anonymous> (http://localhost:5000/scripts/main.js:62:10)
    at https://www.gstatic.com/firebasejs/4.0.0/firebase.js:466:375
    at fc (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:328:165)
    at bf (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:393:215)
    at cf (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:392:403)
    at Qg.g.Gb (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:483:287)
    at Ag.g.wd (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:447:251)
    at og.wd (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:437:364)
    at Yf.Xf (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:435:281) 

firebase.js:328 Uncaught TypeError: div.setAttribute is not a function
    at.displayMessage (main.js:226)
    at .<anonymous> (main.js:62)
    at firebase.js:466
    at fc (firebase.js:328)
    at bf (firebase.js:393)
    at cf (firebase.js:392)
    at Qg.g.Gb (firebase.js:483)
    at Ag.g.wd (firebase.js:447)
    at og.wd (firebase.js:437)
    at Yf.Xf (firebase.js:435)

FIREBASE WARNING: Exception was thrown by user callback. TypeError: div.setAttribute is not a function
    at.displayMessage (http://localhost:5000/scripts/main.js:226:9)
    at.<anonymous> (http://localhost:5000/scripts/main.js:62:10)
    at https://www.gstatic.com/firebasejs/4.0.0/firebase.js:466:375
    at fc (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:328:165)
    at bf (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:393:215)
    at cf (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:392:403)
    at Qg.g.Gb (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:483:287)
    at Ag.g.wd (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:447:251)
    at og.wd (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:437:364)
    at Yf.Xf (https://www.gstatic.com/firebasejs/4.0.0/firebase.js:435:281) 

Uncaught TypeError: div.setAttribute is not a function
    at.displayMessage (main.js:226)
    at.<anonymous> (main.js:62)
    at firebase.js:466
    at fc (firebase.js:328)
    at bf (firebase.js:393)
    at cf (firebase.js:392)
    at Qg.g.Gb (firebase.js:483)
    at Ag.g.wd (firebase.js:447)
    at og.wd (firebase.js:437)
    at Yf.Xf (firebase.js:435)

**Comment by apsrcreatix** [comment]
Hey friend,
If you are using functions option provided by firebase then check the functions log.There you may find the root of this problem.I am not sure that this the main problem with it but I am getting the same problem. It happened after so many requests made to the server provided for function.
If you come to the solution please let me know too.
Thanks,
Aditya Rajput

**Comment by nicolasgarnier** [comment]
@codesdk very strange. [queryseletcor](https://caniuse.com/#feat=queryselector) should be available in most browsers. can you make sure you were using a recent browser?

**Comment by nicolasgarnier** [comment]
Closing for inactivity
