### ISSUE TITLE
Step 8 Error occurred while parsing your function triggers.

### ISSUE THREAD

**Issue by kavaskar** [firebase/friendlychat-web#253]
Error: Error occurred while parsing your function triggers.

/private/var/folders/g9/f487vmzs5s30bg_g1_x2z4hm0000gn/T/fbfn_1672bHPIjYDuzY4c/index.js:1
(function (exports, require, module, __filename, __dirname) { import { event } from 'firebase-functions/lib/providers/analytics';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:18:11

**Comment by kavaskar** [comment]
mistake on my in. Included modules thats not being used
