### ISSUE TITLE
[Error] Firebase Deploy blocked by Firebase-Debug.log permissions

### ISSUE THREAD

**Issue by tkottke90** [firebase/friendlychat-web#269]
Hey All,

**Browser:** Chrome, Firefox
**OS:** Windows 10
**IDE:** VSCode

**Steps to reproduce:**
1) Follow [Firebase Web CodeLab](https://codelabs.developers.google.com/codelabs/firebase-web/#12) to step 13
2) Per the instructions in step 13, run:
` firebase deploy `
3) All steps in deploy process are successful except deploying to firebase when I get this error: 

[2018-04-05T17:53:21.075Z] Error: EPERM: operation not permitted, scandir 'C:\Users\Thomas\Documents\GitHub\Google Firebase CodeLabs\friendlychat-web\web-start\firebase-debug.log'
    at Object.fs.readdirSync (fs.js:912:18)
    at GlobSync._readdir (C:\Users\Thomas\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\sync.js:288:41)
    at GlobSync._readdirInGlobStar (C:\Users\Thomas\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\sync.js:245:17)
    at GlobSync._readdir (C:\Users\Thomas\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\sync.js:276:17)
    at GlobSync._processReaddir (C:\Users\Thomas\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\sync.js:137:22)
    at GlobSync._process (C:\Users\Thomas\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\sync.js:132:10)
    at GlobSync._processGlobStar (C:\Users\Thomas\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\sync.js:380:10)
    at GlobSync._process (C:\Users\Thomas\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\sync.js:130:10)
    at new GlobSync (C:\Users\Thomas\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\sync.js:48:10)
    at globSync (C:\Users\Thomas\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\sync.js:26:10)

**Expected Result**
Deployment of app to firebase hosting

**Actual Result**
Error listed above

**Additional Info**
I checked the firebase-debug.log file, I have absolutely no access to this file even as an administrator on my device.   I can't even change the permission level on the file or delete the file.  Wondering if anyone else is experiencing this.  I did not see an issue related to this yet posted.

**Comment by nicolasgarnier** [comment]
@tkottke90 not sure what's the cause of your issue but it may be related to this issue: https://github.com/npm/npm/issues/17747

You could try the solutions they talk about towards the end. e.g.:

>In my case it was caused by Windows Defender realtime protection on Windows 10. As soon as i added an exception for the node.exe process all errors where gone!

>Beautifull solution. Worked here, too.
After executing "npm install scandir -g" like @micsel suggested.
Thanks @micsel.

I'd upgrade NPM and upgrade Node.
