### ISSUE TITLE
Google sign in friendly chat and quickstart android blinks and nothing happens

### ISSUE THREAD

**Issue by VitalyKononenko** [firebase/friendlychat-web#426]
I added SHA1 key to the firebase. I tried on virtual device and Huawei phone.

This is and exctract from logcat for quickstart-android java.
2019-05-26 13:37:10.161 1919-1942/system_process E/BatteryExternalStatsWorker: no controller energy info supplied for wifi
2019-05-26 13:37:10.460 6564-6597/com.google.firebase.quickstart.auth E/GraphResponse: {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Some of the aliases you requested do not exist: REPLACE_ME}
2019-05-26 13:37:10.582 6564-6597/com.google.firebase.quickstart.auth E/GraphResponse: {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Some of the aliases you requested do not exist: REPLACE_ME}
2019-05-26 13:37:11.169 3811-4745/com.google.android.gms.ui E/bwxj: *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
        Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
    java.lang.RuntimeException: ManagedChannel allocation site
        at bwxk.<init>(:com.google.android.gms@16089022@16.0.89 (040700-239467275):1)
        at bwxj.<init>(:com.google.android.gms@16089022@16.0.89 (040700-239467275):2)
        at bwxj.<init>(:com.google.android.gms@16089022@16.0.89 (040700-239467275):1)
        at bwqb.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):13)
        at rke.a(:com.google.android.gms@16089022@16.0.89 (040700-239467275):39)
        at rke.a(:com.google.android.gms@16089022@16.0.89 (040700-239467275):60)
        at com.google.android.gms.signin.activity.SignInChimeraActivity.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):32)
        at aoyy.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at rrt.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):32)
        at rrt.run(:com.google.android.gms@16089022@16.0.89 (040700-239467275):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at rxx.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2019-05-26 13:37:11.170 3811-4745/com.google.android.gms.ui E/bwxj: *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
        Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
    java.lang.RuntimeException: ManagedChannel allocation site
        at bwxk.<init>(:com.google.android.gms@16089022@16.0.89 (040700-239467275):1)
        at bwxj.<init>(:com.google.android.gms@16089022@16.0.89 (040700-239467275):2)
        at bwxj.<init>(:com.google.android.gms@16089022@16.0.89 (040700-239467275):1)
        at bwqb.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):13)
        at rke.a(:com.google.android.gms@16089022@16.0.89 (040700-239467275):39)
        at rke.a(:com.google.android.gms@16089022@16.0.89 (040700-239467275):60)
        at com.google.android.gms.signin.activity.SignInChimeraActivity.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):32)
        at aoyy.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at rrt.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):32)
        at rrt.run(:com.google.android.gms@16089022@16.0.89 (040700-239467275):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at rxx.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)

**Comment by jhuleatt** [comment]
Hi there, this is the repository for the JavaScript (Web) friendlychat source. Please post this in [friendlychat-android](https://github.com/firebase/friendlychat-android/issues) instead. When you do, tell us if you've tried running the completed code (https://github.com/firebase/friendlychat-android/tree/master/build-android), and if that still has the same error.
